title: Test title
author: me 
email: your-email@domain.com
description: > This is my awesome description

# this means to ignore newlines until "baseurl:"


# social links
twitter_username: @thisisme
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
